### ISSUE TITLE
[Setting] 아키텍쳐 설계

### ISSUE THREAD

**Issue by Ojongseok** [Kusitms-NumberOne/Android#1]
**Issue**
- 이슈 내용: MVVM + Clean Architecture 설계

**Branch Name**
- 생성 브랜치 이름 : `setting_jongseok`

**To-Do List**
- [x] 레이어 분리, 폴더링
- [x] DI 적용(Hilt)
- [x] CallAdapter 생성 및 Retrofit 리턴 타입에 적용
- [x] Base 코드 작성(일단 BaseActivity, BaseFragment 만)
- [x] Presentation, Domain, Data Layer까지 사이클 확인
