### ISSUE TITLE
[Refactor] 토큰 관리하는 TokenManager 보완사항

### ISSUE THREAD

**Issue by Ojongseok** [Kusitms-NumberOne/Android#11]
**Issue**
- 이슈 내용: TokenManager 다른 클래스에 hilt로 주입하고 싶음...

**Branch Name**
- 생성 브랜치 이름 : `feat/naver_login`

**To-Do List**
- [x] Activity, Fragment에 생성자로 주입하기(BaseActivity, BaseFragment 생성자때문에 안되는건지...)
- [ ] OkHttp 인터셉터에 Header로 자동으로 전송될 수 있도록 마이그레이션
- [x] TokenManager에 accessToken collect하는 로직에서 기존 토큰 만료된 경우에 액티비티 두 번 실행되는 버그 있음,,
- [ ] 소셜로그인 로그아웃

**Comment by Ojongseok** [comment]
LoginActivity에 몰려있는 자동로그인 로직 SplashActivity에서 체크하도록 일부 옮겨야 할듯

**Comment by seunghee17** [comment]
activity나 fragment는 원래 생성자로 주입이 안되지 않나..?
