### ISSUE TITLE
[Feat] 홈화면 UI 구성 및 기능 개발

### ISSUE THREAD

**Issue by Ojongseok** [Kusitms-NumberOne/Android#17]
**Issue**
- 이슈 내용: 홈화면 UI 구성 및 기능 개발

**Branch Name**
- 생성 브랜치 이름 : `feat/home`

**To-Do List**
- [x] 홈화면 UI 구성
- [x] 카카오맵, 네이버맵, 티맵 길찾기 API 연결
- [x] 서버 API 연결 (체크리스트 제외 완료)
- [x] 체크리스트 예쁘게,, (ViewPager로)
- 위치 관련 예외처리
  - [x] 위치 권한 확인
  - [x] 위치가 켜져있는 경우 최근 재난문자, 주변 대피소 API 요청
  - [x] 위치가 켜져있지 않는 경우 팝업을 띄워주면서 앱 종료 / 위치 켜도록 유도
