### ISSUE TITLE
[Feat] 펀딩화면 UI 구성 및 기능 개발

### ISSUE THREAD

**Issue by Ojongseok** [Kusitms-NumberOne/Android#18]
**Issue**
- 이슈 내용: 펀딩화면 UI 구성 및 기능 개발

**Branch Name**
- 생성 브랜치 이름 : `feat/funding`

**To-Do List**
- [x] 펀딩 관련 화면 UI 구성
- [x] 인앱결제 기능
- [x] 서버 API  연결
- [x] 상단 응원메시지 두 줄로 흐르는 뷰 구성
