### ISSUE TITLE
[Feat] Jetpack Bottom Navigation 적용

### ISSUE THREAD

**Issue by Ojongseok** [Kusitms-NumberOne/Android#2]
**Issue**
- 이슈 내용: Jetpack Bottom Navigation 적용

**Branch Name**
- 생성 브랜치 이름 : `setting_jongseok`

**To-Do List**
- [x] menu, navigation xml 생성
- [x] navigation_graph 생성
- [x] bottom navigation bar 메뉴 선택에 따라 fragment 이동
- [x] navigation controller로 fragment 이동

**Comment by Ojongseok** [comment]
Android Studio Giraffe에서 safe argument 할당이 안되는 버그
https://stackoverflow.com/questions/61492507/safeargs-argument-not-found-in-navdirections

너무 크리티컬한데,,,
